Models/Game.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace TournamentApplication.Models
{
    public class Game
    {
        public int GameId { get; set; }
        public string Publisher { get; set; }
        public string Image { get; set; }
        public string Url { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public GameTypeEnum GameType { get; set; }

    }
}

Controllers/GamesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using TournamentApplication.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using System;

namespace TournamentApplication.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class GamesController : ControllerBase
    {
        private readonly ApplicationDbContext _db;
        public GamesController(ApplicationDbContext db)
        {
            _db = db;
        }
        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _db.Game.ToListAsync() });
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var gameFromDb = _db.Game.FirstOrDefault(u => u.GameId == id);
            if (gameFromDb == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _db.Game.Remove(gameFromDb);
            await _db.SaveChangesAsync();
            return Json(new { success = true, message = "delete succesful" });

        }

        private IActionResult Json(object p)
        {
            throw new NotImplementedException();
        }
    }
}

Pages/GameList/Games.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TournamentApplication.Models;

namespace TournamentApplication.Pages
{
    public class GamesModel : PageModel
    {
        private readonly ApplicationDbContext _db;

        public GamesModel(ApplicationDbContext db)
        {
            _db = db;
        }

        public IEnumerable<Game> Games { get; set; }

        public async Task OnGet()
        {
            Games = await _db.Game.ToListAsync();
        }
        public async Task<IActionResult> OnPostDeleteGame(int id)
        {
            var game = await _db.Game.FindAsync(id);
            if(game == null)
            {
                return NotFound();
            }
            _db.Game.Remove(game);
            await _db.SaveChangesAsync();

            return RedirectToPage("Games");
        }
    }
}

Pages/GameList/UpsertGame.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TournamentApplication.Models;

namespace TournamentApplication.Pages.GameList
{
    public class UpsertGameModel : PageModel
    {
        private ApplicationDbContext _db;

        public UpsertGameModel(ApplicationDbContext db)
        {
            _db = db;
        }
        [BindProperty]
        public Game Game { get; set; }
        public async Task<IActionResult> OnGet(int? id)
        {
            Game = new Game();
            if(id == null)
            {
                return Page();
            }
            Game = await _db.Game.FirstOrDefaultAsync(u => u.GameId == id);
            if(Game == null)
            {
                return NotFound();
            }
            return Page();
        }
        public async Task<IActionResult> OnPost()
        {
            if(ModelState.IsValid)
            {
                if (Game.GameId == 0)
                {
                    _db.Game.Add(Game);
                }
                else
                {
                    _db.Game.Update(Game);
                }

                await _db.SaveChangesAsync();

                return RedirectToPage("Games");
            }

                return RedirectToPage();
        }
    }
}

Pages/GameList/Games.cshtml
@page
@model TournamentApplication.Pages.GamesModel


<div class="container row p-0 m-0">
    <div class="col-9">
        <h3>Game List</h3>
    </div>
    <div class="col-4">
        <a asp-page="UpsertGame" class="btn btn-info form-control text-white">New Game</a>
    </div>

    <div class="card-columns col-12 border p-3 mt-3">
        <form method="post">
            @foreach (var game in Model.Games)
        {
            <div class="card">
                <div class="card-img" style="background-image: url('@game.Image');"></div>
                <div class="card-body">
                    <h5 class="card-title">@game.Title</h5>
                            @Html.DisplayFor(m => game.Publisher)
                            @Html.DisplayFor(m => game.Description)
                            <button asp-page-handler="DeleteGame" asp-route-id="@game.GameId" onclick="return confirm ('Are you sure you want to delete this game?')" class="btn btn-danger btn-sm">Delete</button>
                            <a asp-page="UpsertGame" asp-route-id="@game.GameId" class="btn btn-success btn-sm text-white">Edit</a>
                </div>
            </div>
        }
        </form>
    </div>
    </div>

Pages/GameList/UpsertGame.cshtml
@page
@model TournamentApplication.Pages.GameList.UpsertGameModel

<h2 class="text-info">@(Model.Game.GameId!=0? "Edit" : "Create") the game</h2>

<div class="border container" style="padding:30px;">
    <form method="post">
        @if (Model.Game.GameId != 0)
        {
            <input type="hidden" asp-for="Game.GameId" />
        }
        <div class="text-danger" asp-validation-summary="ModelOnly">
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Game.Publisher">Publisher</label>
            </div>
            <div class="col-6">
                <input asp-for="Game.Publisher" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Game.Image">Image URL</label>
            </div>
            <div class="col-6">
                <input asp-for="Game.Image" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Game.Title">Game name</label>
            </div>
            <div class="col-6">
                <input asp-for="Game.Title" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Game.Description">Tournament type</label>
            </div>
            <div class="col-6">
                <input asp-for="Game.Description" class="form-control" />
            </div>
        </div>
        <div class="form-group row">
            <div class="col-2 offset-3">
                <button type="submit" class="btn btn-primary form-control">@(Model.Game.GameId!=0? "Update" : "Create")</button>
            </div>
            <div class="col-2">
                <a asp-page="Games" class="btn btn-success form-control">Back to list</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}